Italomax/Loja-de-Games

- src/main/resources/application.properties
@fabiolasoufer [Task: Criando banco de dados]
> @fabiolasoufer [Task: Criando banco de dados]

- pom.xml
- src/main/java/com/lojagames/lojaGames/models/Categoria.java
@Samara-Alves [Task:Adicionando categoria model]
> @Samara-Alves [Task:Adicionando categoria model]

- src/main/java/com/lojagames/lojaGames/controller/CategoriaController.java
@anita-falchi: [Task: Criando endPoint FindAll Categoria]
> @anita-falchi: [Task: Criando endPoint FindAll Categoria]

- src/main/java/com/lojagames/lojaGames/controller/CategoriaController.java
- src/main/java/com/lojagames/lojaGames/models/Categoria.java
- src/main/java/com/lojagames/lojaGames/repository/CategoriaRepository.java
@JeanLRC [Task: CREATE endpoints findById e findByDescricao Categoria]
> @JeanLRC [Task: CREATE endpoints findById e findByDescricao Categoria]

- src/main/java/com/lojagames/lojaGames/controller/CategoriaController.java
@HikaruYamanaka [Task: Finalizando CRUD categoria]
> @HikaruYamanaka [Task: Finalizando CRUD categoria]

- src/main/java/com/lojagames/lojaGames/models/Categoria.java
- src/main/java/com/lojagames/lojaGames/models/Produto.java
@fabiolasoufer [Task: CREATE model Produto e Relacionamento de tabelas]
> @fabiolasoufer [Task: CREATE model Produto e Relacionamento de tabelas]

- src/main/java/com/lojagames/lojaGames/controller/ProdutoController.java
- src/main/java/com/lojagames/lojaGames/repository/ProdutoRepository.java
@Samara-Alves[Task:criando camada de produto controller]
> @Samara-Alves[Task:criando camada de produto controller]

- src/main/java/com/lojagames/lojaGames/controller/ProdutoController.java
@bustos00 [Task: Criando controller Id]
> @bustos00 [Task: Criando controller Id]

- src/main/java/com/lojagames/lojaGames/controller/ProdutoController.java
@anita-falchi: [Task: adicionando controller findByTitulo]
> @anita-falchi: [Task: adicionando controller findByTitulo]

- src/main/java/com/lojagames/lojaGames/controller/ProdutoController.java
@RafaelCasotti [Task: CREATE Post Controller]
> @RafaelCasotti [Task: CREATE Post Controller]

- src/main/java/com/lojagames/lojaGames/controller/ProdutoController.java
@HikaruYamanaka [Task: Finalizando CRUD de Produto]
> @HikaruYamanaka [Task: Finalizando CRUD de Produto]

- src/main/java/com/lojagames/lojaGames/models/Categoria.java
@JeanLRC [Task: MODIFY categoria relation to cascade.remove]
> @JeanLRC [Task: MODIFY categoria relation to cascade.remove]

- src/main/resources/application.properties
@RafaelCasotti [Task: Atualizando username e password do banco de dados]
> @RafaelCasotti [Task: Atualizando username e password do banco de dados]

- pom.xml
- src/main/java/com/lojagames/lojaGames/models/Usuario.java
@fabiolasoufer [Task: Adicionando dependencias e Criando camada model]
> @fabiolasoufer [Task: Adicionando dependencias e Criando camada model]

- src/main/java/com/lojagames/lojaGames/models/Produto.java
- src/main/java/com/lojagames/lojaGames/models/UserLogin.java
- src/main/java/com/lojagames/lojaGames/repository/CategoriaRepository.java
- src/main/java/com/lojagames/lojaGames/seguranca/BasicSecurityConfig.java
@HikaruYamanaka [Task: Criando camada UserLogin e iniciando Security]
> @HikaruYamanaka [Task: Criando camada UserLogin e iniciando Security]

- src/main/java/com/lojagames/lojaGames/seguranca/UserDetailsImpl.java
- src/main/java/com/lojagames/lojaGames/seguranca/UserDetailsServiceImpl.java
@JeanLRC [Task: Criando UserDetailsImpl e UserDetailsServiceImpl]
> @JeanLRC [Task: Criando UserDetailsImpl e UserDetailsServiceImpl]

- src/main/java/com/lojagames/lojaGames/repository/UsuarioRepository.java
- src/main/java/com/lojagames/lojaGames/seguranca/UserDetailsServiceImpl.java
@RafaelCasotti [TASK: Create Repositorio Usuario]
> @RafaelCasotti [TASK: Create Repositorio Usuario]

- src/main/java/com/lojagames/lojaGames/repository/ProdutoRepository.java
- src/main/java/com/lojagames/lojaGames/service/UsuarioService.java
@bustos00 [task: Criando classe UsuarioService]
> @bustos00 [task: Criando classe UsuarioService]

- src/main/java/com/lojagames/lojaGames/controller/UsuarioController.java
@Samara-Alves [Task:Criando Usuario controller]
> @Samara-Alves [Task:Criando Usuario controller]

- src/main/resources/application.properties
@fabiolasoufer [Task: Corrigindo BUG referência circular]
> @fabiolasoufer [Task: Corrigindo BUG referência circular]
